export const GRAPH_CONSTANTS = {
    NODE_DIAMETER: 96,
    NODE_RADIUS: 48,
    EDGE_STROKE_WIDTH: 2,
    ARROW_SIZE: 10,
    MIN_FONT_SIZE: 4,
    MAX_FONT_SIZE: 12,
    EDGE_TEXT_PADDING: 15,
    EDGE_MAX_WIDTH: 150,
    LINE_HEIGHT: 1.2,
    CANVAS_SIZE: 90000
} as const; 